# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS build

# Install dependencies
WORKDIR /app
COPY package*.json tsconfig.json ./
COPY src ./src

# Install and build
RUN npm install --production=false --ignore-scripts && npm run build

# Runtime image
FROM node:lts-alpine
WORKDIR /app

# Copy built files and dependencies
COPY --from=build /app/build ./build
COPY package*.json ./
RUN npm install --production --ignore-scripts

# Expose nothing (stdio)

# Entrypoint
ENTRYPOINT ["node", "build/index.js"]
